#dev
server:
  address: localhost
  port: 8080

spring:
#  config:
#    activate:
#      on-profile: dev
  thymeleaf:
    prefix: classpath:template/
    suffix: .html
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://183.111.227.104:3306/foodie?useSSL=false&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: Foodie123!@#
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

logging:
  level:
    org.hibernate.type: trace

---

# deploy{to be adding}
