#dev
server:
  address: localhost
  port: 8080
  max-http-header-size: 400000

spring:
  #  config:
  #    activate:
  #      on-profile: dev
  thymeleaf:
    prefix: classpath:template/
    suffix: .html
    cache: false

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://183.111.227.104:3306/foodie?useSSL=false&characterEncoding=utf8&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull
    username: test
    password: Foodie123!@#

  jpa:
    hibernate:
      ddl-auto: none #update
    show-sql: false
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 862373463465-qpf1kdbln2gt0q7likoai6se56spj3bb.apps.googleusercontent.com
            client-secret: 8YOT8_U-HEJJwAyOk0p85SAU
            scope:
              - email
              - profile

          kakao:
            client-id: 70474aee6f5d5b3f646a752c232a52f4
            client-secret: foodie
            client-name: kakao
            redirect-uri: http://foodie365.cafe24.com/login/oauth2/code/kakao
            client-authentication-method: POST
            authorization-grant-type: authorization_code

          naver:
            client-id: d58QPtWutbf8KvOcNeHT
            client-secret: sj1Zv1B2AI
            client-name: naver
            redirect-uri: http://foodie365.cafe24.com/login/oauth2/code/naver
            client-authentication-method: POST
            authorization-grant-type: authorization_code

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: kakao_account

          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
  mail:
    host: smtp.gmail.com
    port: 587
    username: foodiepicure@gmail.com
    password: 584472ys&
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 25MB


#logging:
#  level:
#    org.hibernate.type: trace

# deploy{to be adding}