#dev
server:
  address: localhost
  port: 8080

spring:
  config:
    activate:
      on-profile: dev

  thymeleaf:
    prefix: classpath:template/
    suffix: .html
    cache: false

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://183.111.227.104:3306/foodie?useSSL=false&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: Foodie123!@#
  j
  pa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 862373463465-qpf1kdbln2gt0q7likoai6se56spj3bb.apps.googleusercontent.com
            client-secret: 8YOT8_U-HEJJwAyOk0p85SAU
            scope:
              - email
              - profile

          kakao:
            client-id: 70474aee6f5d5b3f646a752c232a52f4
            client-secret: foodie
            client-name: Kakao
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-authentication-method: POST
            authorization-grant-type: authorization_code

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: kakao_account


logging:
  level:
    org.hibernate.type: trace


---

# deploy{to be adding}